-- Data migrated from SQLite licenses.db
USE lineranger_automation;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- t_users: 2 rows
INSERT INTO t_users (id, username, email, hashed_password, role, is_active, created_at) VALUES (1, 'natchapakj', NULL, '$2b$12$yK9VxwCMKXk73G.7ldXbV.UY49KdMZOPOkTxkBax9r1eQ910Xgd/O', 'admin', 1, '2025-12-14 08:31:59.488611');
INSERT INTO t_users (id, username, email, hashed_password, role, is_active, created_at) VALUES (2, 'user', 'test@gmail.com', '$2b$12$vtWeewqxHGqgkMdwD7H.NuF0WaSHA2z713NkFYP5kRcBUfZGP7YbW', 'user', 1, '2025-12-17 12:31:21.205089');

-- t_licenses: 0 rows

-- t_workflows: 2 rows
INSERT INTO t_workflows (id, name, description, screen_width, screen_height, valid_from, valid_until, is_master, mode_name, month_year, created_at, updated_at) VALUES (1, 'daily-login', '', 960, 540, NULL, NULL, 0, 'daily-login', '2025-12', '2025-12-14 08:32:14.925991', '2025-12-21 12:48:17.235916');
INSERT INTO t_workflows (id, name, description, screen_width, screen_height, valid_from, valid_until, is_master, mode_name, month_year, created_at, updated_at) VALUES (2, 'new-work-flow', '', 960, 540, NULL, NULL, 1, 'daily-login', '2025-12', '2025-12-21 06:41:31.582516', '2025-12-21 12:48:17.249858');

-- t_workflow_templates: 13 rows
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (1, 'close_pop_up', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_pop_up_20251215_200157.png', '', 797, 53, 30, 28, '2025-12-15 13:01:57.383744');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (2, 'close_popup', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_popup_20251215_200327.png', '', 788, 41, 48, 47, '2025-12-15 13:03:27.237146');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (3, 's', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\s_20251215_200548.png', '', 790, 44, 44, 39, '2025-12-15 13:05:48.712943');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (4, 'รรร', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\รรร_20251215_202218.png', '', 788, 41, 48, 45, '2025-12-15 13:22:18.964981');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (5, 'gift', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\gift_20251215_205428.png', '', 726, 451, 75, 64, '2025-12-15 13:54:28.903260');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (6, 'Gacha', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_20251221_014426.png', '', 616, 139, 99, 28, '2025-12-20 18:44:26.643320');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (7, 'Gacha_ok_btn', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_ok_btn_20251221_014514.png', '', 417, 388, 128, 37, '2025-12-20 18:45:14.390740');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (8, 'open_gacha_btn', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\open_gacha_btn_20251221_014600.png', '', 180, 432, 176, 41, '2025-12-20 18:46:00.185993');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (9, 'one_more_time_open', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\one_more_time_open_20251221_014746.png', '', 495, 418, 143, 40, '2025-12-20 18:47:46.114943');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (10, 'Accecpt_all_gift', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Accecpt_all_gift_20251221_015736.png', '', 618, 451, 163, 34, '2025-12-20 18:57:36.580725');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (11, 'Gift_ok', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', '', 494, 342, 120, 28, '2025-12-21 07:30:31.899969');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (12, 'open_gacha2', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\open_gacha2_20251221_170029.png', '', 187, 431, 170, 43, '2025-12-21 10:00:29.309399');
INSERT INTO t_workflow_templates (id, name, file_path, description, region_x, region_y, region_width, region_height, created_at) VALUES (13, 'gacha_ruby', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\gacha_ruby_20251221_173006.png', '', 183, 433, 174, 44, '2025-12-21 10:30:06.887806');

-- t_workflow_template_sets: 0 rows

-- t_workflow_steps: 27 rows
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (1, 1, 0, 'start_game', NULL, NULL, NULL, NULL, 300, NULL, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Start game', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (2, 1, 1, 'wait', NULL, NULL, NULL, NULL, 300, 30000, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Wait 1000ms', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (3, 1, 2, 'loop_click', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_popup_20251215_200327.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Loop click until not found', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (4, 1, 3, 'wait', NULL, NULL, NULL, NULL, 300, 60, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Wait 1000ms', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (5, 1, 4, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\gift_20251215_205428.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (6, 1, 5, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Accecpt_all_gift_20251221_015736.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (7, 1, 6, 'loop_click', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_popup_20251215_200327.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (8, 1, 7, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_ok_btn_20251221_014514.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (9, 1, 8, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_20251221_014426.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (10, 1, 9, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_ok_btn_20251221_014514.png', NULL, 0.8, 0, 1, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (11, 1, 10, 'wait', NULL, NULL, NULL, NULL, 300, 30000, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Wait 1000ms', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (12, 2, 0, 'start_game', NULL, NULL, NULL, NULL, 300, NULL, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Start game', NULL, 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (13, 2, 1, 'wait', 91, 399, NULL, NULL, 300, 30000, NULL, NULL, 0.8, 0, 0, 60, NULL, 1.0, 'click', NULL, NULL, NULL, 'Wait 30000ms', 'daily-login', 20, 3, 1.5, 2.0, '[41, 89, 156]', 30, 3.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (14, 2, 2, 'loop_click', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_popup_20251215_200327.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 40, 5, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (15, 2, 3, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\gift_20251215_205428.png', NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (16, 2, 4, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Accecpt_all_gift_20251221_015736.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (17, 2, 5, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (18, 2, 6, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (19, 2, 7, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\close_popup_20251215_200327.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'daily-login', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (20, 2, 8, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gacha_20251221_014426.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (21, 2, 9, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', NULL, 0.8, 0, 1, 30, 2, 3.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (22, 2, 10, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\open_gacha2_20251221_170029.png', NULL, 0.8, 0, 0, 30, 4, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (23, 2, 11, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (24, 2, 12, 'wait_for_color', 630, 431, NULL, NULL, 300, 1500, NULL, NULL, 0.8, 0, 0, 60, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, '[206, 186, 8]', 30, 10.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (25, 2, 13, 'gacha_check', NULL, NULL, NULL, NULL, 300, NULL, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, '{"x": 320, "y": 140, "width": 320, "height": 60}', '["Fairy Cony", "Mail Carrier PEW"]', 'E:/Window backups/Project/Project/lrg-bot');
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (26, 2, 14, 'image_match', NULL, NULL, NULL, NULL, 300, NULL, 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\Gift_ok_20251221_143031.png', NULL, 0.8, 0, 0, 30, 2, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, NULL, NULL, 1, 100, NULL, NULL, NULL);
INSERT INTO t_workflow_steps (id, workflow_id, order_index, step_type, x, y, end_x, end_y, swipe_duration_ms, wait_duration_ms, template_path, template_name, threshold, match_all, skip_if_not_found, max_wait_seconds, max_retries, retry_interval, on_match_action, condition_type, goto_step_on_true, goto_step_on_false, description, group_name, max_iterations, not_found_threshold, click_delay, retry_delay, expected_color, tolerance, check_interval, loop_group_name, stop_template_path, stop_on_not_found, loop_max_iterations, ocr_region, target_characters, gacha_save_folder) VALUES (27, 2, 15, 'repeat_group', NULL, NULL, NULL, NULL, 300, NULL, NULL, NULL, 0.8, 0, 0, 10, NULL, 1.0, 'click', NULL, NULL, NULL, 'Image match', 'gacha', 20, 3, 1.5, 2.0, NULL, 30, 1.0, 'gacha', 'C:\\Users\\welcome\\Desktop\\Project\\lrg-bot\\app\\services\\..\\..\\workflow_templates\\gacha_ruby_20251221_173006.png', 1, 100, NULL, NULL, NULL);

-- t_template_set_workflow_assoc: 0 rows

-- t_mode_configurations: 0 rows

SET FOREIGN_KEY_CHECKS = 1;
